from enum import Enum, auto
from datetime import timedelta


class Timeframe:
    M1 = 1
    M5 = 5
    M15 = 15
    M30 = 30
    H1 = 60
    H4 = 240

    ALL = [M1, M5, M15, M30, H1, H4]
    MT5_MAP = {M1: 1, M5: 5, M15: 15, M30: 30, H1: 60, H4: 240}
    LABELS = {M1: "M1", M5: "M5", M15: "M15", M30: "M30", H1: "H1", H4: "H4"}
    N_CANDLES_MAP = {M1: 100, M5: 100, M15: 80, M30: 60, H1: 50, H4: 40}


class TradeDirection(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    WEAK_BUY = "WEAK_BUY"
    WEAK_SELL = "WEAK_SELL"


class OrderType(Enum):
    MARKET = auto()
    LIMIT = auto()
    STOP = auto()


class OrderStatus(Enum):
    PENDING = auto()
    OPEN = auto()
    CLOSED = auto()
    CANCELLED = auto()
    REJECTED = auto()


class MarketRegime(Enum):
    STRONG_TRENDING_BULLISH = "STRONG_TRENDING_BULLISH"
    WEAK_TRENDING_BULLISH = "WEAK_TRENDING_BULLISH"
    STRONG_TRENDING_BEARISH = "STRONG_TRENDING_BEARISH"
    WEAK_TRENDING_BEARISH = "WEAK_TRENDING_BEARISH"
    SIDEWAYS = "SIDEWAYS"
    CONSOLIDATION = "CONSOLIDATION"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    NEWS_DRIVEN = "NEWS_DRIVEN"


class TrendDirection(Enum):
    STRONG_BULLISH = "STRONG_BULLISH"
    BULLISH = "BULLISH"
    WEAK_BULLISH = "WEAK_BULLISH"
    STRONG_BEARISH = "STRONG_BEARISH"
    BEARISH = "BEARISH"
    WEAK_BEARISH = "WEAK_BEARISH"
    SIDEWAYS = "SIDEWAYS"
    CONSOLIDATION = "CONSOLIDATION"


class MarketStructure(Enum):
    HIGHER_HIGH = "HH"
    LOWER_HIGH = "LH"
    HIGHER_LOW = "HL"
    LOWER_LOW = "LL"
    BREAK_OF_STRUCTURE = "BOS"
    CHANGE_OF_CHARACTER = "CHOCH"
    UNDEFINED = "UNDEFINED"


class SignalStrength(Enum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    NONE = "NONE"


class CandlePattern(Enum):
    HAMMER = "HAMMER"
    INVERTED_HAMMER = "INVERTED_HAMMER"
    PIN_BAR = "PIN_BAR"
    DOJI = "DOJI"
    BULLISH_ENGULFING = "BULLISH_ENGULFING"
    BEARISH_ENGULFING = "BEARISH_ENGULFING"
    MORNING_STAR = "MORNING_STAR"
    EVENING_STAR = "EVENING_STAR"
    SHOOTING_STAR = "SHOOTING_STAR"
    THREE_WHITE_SOLDIERS = "THREE_WHITE_SOLDIERS"
    THREE_BLACK_CROWS = "THREE_BLACK_CROWS"
    NONE = "NONE"


class PriceActionPattern(Enum):
    LIQUIDITY_GRAB = "LIQUIDITY_GRAB"
    REJECTION = "REJECTION"
    RETEST = "RETEST"
    MOMENTUM_CANDLE = "MOMENTUM_CANDLE"
    BREAKOUT = "BREAKOUT"
    FAKE_BREAKOUT = "FAKE_BREAKOUT"
    FAKE_BREAKDOWN = "FAKE_BREAKDOWN"
    NONE = "NONE"


class PositionAction(Enum):
    HOLD = "HOLD"
    MOVE_STOP_LOSS = "MOVE_STOP_LOSS"
    TRAILING_STOP = "TRAILING_STOP"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    FULL_CLOSE = "FULL_CLOSE"


class EmergencyLevel(Enum):
    NORMAL = "NORMAL"
    CAUTION = "CAUTION"
    DANGER = "DANGER"
    CRITICAL = "CRITICAL"


class TelegramEvent(Enum):
    BOT_STARTED = "BOT_STARTED"
    OPEN_POSITION = "OPEN_POSITION"
    POSITION_UPDATE = "POSITION_UPDATE"
    TRAILING_STOP_UPDATE = "TRAILING_STOP_UPDATE"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    POSITION_CLOSED = "POSITION_CLOSED"
    LOSS_ALERT = "LOSS_ALERT"
    LEARNING_UPDATE = "LEARNING_UPDATE"
    MODEL_RETRAINED = "MODEL_RETRAINED"
    MODEL_ROLLBACK = "MODEL_ROLLBACK"
    DAILY_REPORT = "DAILY_REPORT"
    WEEKLY_REPORT = "WEEKLY_REPORT"
    MONTHLY_REPORT = "MONTHLY_REPORT"
    EMERGENCY_ALERT = "EMERGENCY_ALERT"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    HEARTBEAT = "HEARTBEAT"
    SKILL_UP = "SKILL_UP"


DATA_DIR = "data"
MODEL_DIR = "models"
RESULTS_DIR = "results"
LOG_DIR = "logs"
HISTORICAL_DIR = f"{DATA_DIR}/historical"
CACHE_DIR = f"{DATA_DIR}/cache"
TRADE_HISTORY_DIR = "learning/trade_history"
PERFORMANCE_LOG_DIR = "learning/performance_logs"
DECISION_LOG_DIR = "learning/decision_logs"
REASONING_LOG_DIR = "learning/reasoning_logs"

MAX_RETRIES = 3
RETRY_DELAY = 2.0
MT5_TIMEOUT = 30.0

EME_FAST = 20
EME_MEDIUM = 50
EME_SLOW = 200

RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
ADX_PERIOD = 14
ATR_PERIOD = 14
BB_PERIOD = 20
BB_STD = 2.0
STOCH_K = 14
STOCH_D = 3

LOOKAHEAD_5 = 5
LOOKAHEAD_10 = 10
LOOKAHEAD_20 = 20

TF_VOTE_WEIGHTS = {5: 3.0, 15: 1.5, 30: 2.0}

ML_WEIGHT = 0.80
INTELLIGENCE_WEIGHT = 0.20

RISK_PER_TRADE = 0.005
MAX_RISK_PER_TRADE = 0.01
MAX_DAILY_DRAWDOWN = 0.03
MAX_HARD_STOP_DRAWDOWN = 0.05
EMERGENCY_CAUTION_DD = 0.03
EMERGENCY_DANGER_DD = 0.04
EMERGENCY_CRITICAL_DD = 0.05

MIN_CONFIDENCE = 55
MIN_MARKET_SCORE = 50
MIN_RISK_REWARD = 2.0

REVERSAL_LOOKBACK_M5 = 3
REVERSAL_LOOKBACK_M15 = 2
REVERSAL_LOOKBACK_M30 = 1
REVERSAL_MAX_TREND_CHANGE_CANDLES = 5

NEW_DATA_WEIGHT = 1.0
DATA_30_DAY_WEIGHT = 1.0
DATA_60_DAY_WEIGHT = 0.75
DATA_90_DAY_WEIGHT = 0.50
DATA_OLD_WEIGHT = 0.25

RETRAIN_TRADE_COUNT = 50
WIN_RATE_DROP_THRESHOLD = 0.10

OOS_SPLIT_RATIO = 0.2
OOS_MIN_TRADES = 20
OOS_WR_THRESHOLD = 50.0
OOS_PF_THRESHOLD = 1.2
OOS_SHARPE_THRESHOLD = 0.5

ADAPTIVE_MEMORY_DAYS = [30, 60, 90]
ADAPTIVE_MEMORY_WEIGHTS = [1.0, 0.75, 0.50, 0.25]

HEARTBEAT_INTERVAL_SECONDS = 300
REPORT_DAILY_HOUR = 0
REPORT_WEEKLY_DAY = 0
REPORT_MONTHLY_DAY = 1
